---
title: "Final Project Analysis Gregg"
output: html_notebook
---

```{r}
oly.data <- subset(Olympic_athlete_events [c(1,3,4,5,6,7,13,15)])
```

BMI calculation: weight (kg) / height (m)^2

```{r}
oly.data$BMI <- (oly.data$Weight / (oly.data$Height/100)^2)
```

```{r}
fm.bmi<- lm(BMI ~ Sex, data=oly.data)
anova(fm.bmi)
fm.bmi.aov <- aov(BMI ~ Sex, data=oly.data)
TukeyHSD(fm.bmi.aov, ordered=TRUE)
```
```{r}
class <- cut(oly.data$Age, breaks = c(10, 20, 30, 40, 70), labels = c("Y","S", "M", "O"), right=FALSE)
oly.data.age <- cbind(oly.data, class)
```

```{r}
fm.bmi.age<- lm(BMI ~ class, data=oly.data.age)
anova(fm.bmi.age)
fm.bmi.age.aov <- aov(BMI ~ class, data=oly.data.age)
TukeyHSD(fm.bmi.age.aov, ordered=TRUE)
```


```{r}
density.gold <- density(oly.data$BMI[oly.data$Medal=="Gold"])
density.silver <- density(oly.data$BMI[oly.data$Medal=="Silver"])
density.bronze <- density(oly.data$BMI[oly.data$Medal=="Bronze"])
plot(density.gold, main ="Density of BMI")
lines(density.silver, lty=2)
lines(density.bronze, lty=3)
```

```{r}
density.m <- density(oly.data$BMI[oly.data$Sex=="M"])
density.f <- density(oly.data$BMI[oly.data$Sex=="F"])
plot(density.m, main ="Density of BMI")
lines(density.f, lty=2)
```
```{r}
Female <- subset(oly.data, Sex== "F")
Male <- subset(oly.data, Sex== "M")
t.test(Female$BMI, Male$BMI)
```

```{r}
t.test(Male$Age, Female$Age)
```
```{r}
library(janitor)
tabyl(oly.data, Sex)
tabyl(usa, Sex)
tabyl(non.usa, Sex)
```

USA athletes= 4273 total, 1615 female
Non-USA athletes= 25908 total, 8735 female

```{r}
prop.test(x=c(1615, 8735), n=c(4273,25908), alternative="greater")
```
USA sends a greater proportion of female athletes to the Olympics when compared to all other teams

BMI of endurance vs strength athletes
```{r}
oly.data.strength <- subset(oly.data[c("Weightlifting", "Gymnastics", "Boxing", "Wrestling")])
oly.data.emdurance <- subset(oly.data[Sport = c("Rowing", "Cycling", "Cross Country Skiing")])
```


